### ISSUE TITLE
Server Error if searching connection between two stations

### ISSUE THREAD

**Issue by marcusschiesser** [marcusschiesser/openbahn-api#3]
What steps will reproduce the problem?
1. When user is Searchin connection between two Stations

What is the expected output? What do you see instead?
The expected output ist the Json Object with the train connection. But actually you can see only
Error: Server Error

The server encountered an error and could not complete your request.
If the problem persists, please report your problem and mention this error message and the query that caused it.

What version of the product are you using? On what operating system?
I am usung the link in the API-Documentation
http://openbahnapi.appspot.com/rest/connections/list?start=Karlruhe%20Hbf&destination=Frankfurt(Main)Hbf&date=25.07.2011

**Comment by marcusschiesser** [comment]
This is the stacktrace:

com.sun.jersey.spi.container.ContainerResponse mapMappableContainerException: The RuntimeException could not be mapped to a response, re-throwing to the HTTP container
java.lang.NullPointerException
    at de.marcusschiesser.dbpendler.server.bahnwrapper.handler.TimeExtractionHandler.startElement(TimeExtractionHandler.java:32)
    at org.htmlparser.sax.XMLReader.doSAX(XMLReader.java:660)
    at org.htmlparser.sax.XMLReader.doSAX(XMLReader.java:668)
    at org.htmlparser.sax.XMLReader.doSAX(XMLReader.java:668)
    at org.htmlparser.sax.XMLReader.doSAX(XMLReader.java:668)
    at org.htmlparser.sax.XMLReader.doSAX(XMLReader.java:668)
    at org.htmlparser.sax.XMLReader.doSAX(XMLReader.java:668)
    at org.htmlparser.sax.XMLReader.doSAX(XMLReader.java:668)
    at org.htmlparser.sax.XMLReader.parse(XMLReader.java:533)
    at de.marcusschiesser.dbpendler.server.bahnwrapper.ConnectionParser.getConnectionTime(ConnectionParser.java:113)
    at de.marcusschiesser.dbpendler.server.bahnwrapper.ConnectionParser.getConnection(ConnectionParser.java:67)
    at de.marcusschiesser.dbpendler.server.storage.ConnectionStorage.getConnection(ConnectionStorage.java:49)
    at de.marcusschiesser.dbpendler.server.ConnectionServerResource.listDaily(ConnectionServerResource.java:71)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:43)
    at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$TypeOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:168)
    at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:71)
    at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:280)
    at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
    at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
    at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
    at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
    at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1341)
    at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1273)
    at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1223)
    at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1213)
    at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:414)
    at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:537)
    at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:699)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
    at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
    at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
    at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
    at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
    at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
    at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
    at org.mortbay.jetty.Server.handle(Server.java:326)
    at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
    at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
    at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
    at com.google.tracing.TraceContext$TraceContextRunnable.runInContext(TraceContext.java:454)
    at com.google.tracing.TraceContext$TraceContextRunnable$1.run(TraceContext.java:461)
    at com.google.tracing.TraceContext.runInContext(TraceContext.java:703)
    at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContextNoUnref(TraceContext.java:338)
    at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContext(TraceContext.java:330)
    at com.google.tracing.TraceContext$TraceContextRunnable.run(TraceContext.java:458)
    at java.lang.Thread.run(Thread.java:679)

**Comment by marcusschiesser** [comment]
Looks like DB changed the generated output. The TimeExtractionHandler must be updated. Anyone using this service wants to do it?

**Comment by johnnycusack** [comment]
I can't tell you for sure what the reason on the page is, just started using your lib, but the problem i found was inside TimeExtractionHandler#startElement()  the attributes.getValue("class") returned null i changed the function to the following so it works now...:

```
@Override
public void startElement(String uri, String localName, String qName,
        Attributes attributes) throws SAXException {

        if (localName.equalsIgnoreCase("td")
                && "overview timelink".equalsIgnoreCase(attributes.getValue("class"))) {
            insideTimelink = 1;
        }
        if (localName.equalsIgnoreCase("td")
                && "overview iphonepfeil".equalsIgnoreCase(attributes.getValue("class"))) {
            insidePrice = 1;
        }
        if (insideTimelink > 0 && "a".equalsIgnoreCase(localName)) {
            anchors.add(attributes.getValue("href"));
        }


}
```

sorry my first time on github... viel erfolg noch ;)

**Comment by marcusschiesser** [comment]
Great, just added you as collaborator to the project. So you can commit this change.

**Comment by claudiug** [comment]
still the same problem. any updates?

**Comment by marcusschiesser** [comment]
I guess you tried the demo on appspot and not the actual code. johnny fixed this issue, so i close it now. Opened a new ticket for updating appspot: https://github.com/marcusschiesser/openbahn-api/issues/5
